Use template parameter for concept constraint check
Android clang will get upset if the 'span' member constant 'extent' is used
in a concept requires statement with the following error:

    error: no member 'extent' in 'span<const unsigned char>'; it has not yet been instantiated

This error does not happen when building pdfium for macOS/Linux/Windows desktop builds.
Looking at other implementations of 'span', none of them use the member constant in
their concept requires statemets, they only use the template parameter '_Extent'.

For now, applying if-def's around the areas that the android clang compiler
was upset about.